import type { AIProvider, AgentEvent, AIProviderName } from '../../../shared/types';
import apiClient from '../api';
import { isUiRelatedTask, CLAUDE_UI_MODEL } from '../uiRouting';

export type { AIProvider, AgentEvent, AIProviderName };

export interface AgentStepResult {
  conversationId: string;
  message: {
    role: string;
    content?: string | null;
    tool_calls?: Array<{ id: string; type: string; function: { name: string; arguments: string } }>;
  };
  finishReason: 'stop' | 'tool_calls' | 'length';
  provider?: string;
  model?: string;
}

export interface StreamChatOptions {
  model?: string;
  conversationId?: string;
  context?: Record<string, unknown>;
  agentMode?: string;
}

/** Resolve which backend provider to use in auto mode */
export function resolveAutoProvider(prompt: string, agentMode?: string): AIProviderName {
  const lower = prompt.toLowerCase();
  if (isUiRelatedTask(prompt)) return 'claude';
  if (agentMode === 'refactor' || agentMode === 'deep' || /\brefactor|architecture|review entire\b/.test(lower)) {
    return 'claude';
  }
  if (/\banalyze|ocr|screenshot|long document\b/.test(lower)) {
    return 'gemini';
  }
  return 'openai';
}

export function resolveAutoModel(prompt: string, agentMode?: string): string | undefined {
  if (isUiRelatedTask(prompt)) return CLAUDE_UI_MODEL;
  if (agentMode === 'refactor' || agentMode === 'deep') return CLAUDE_UI_MODEL;
  if (agentMode === 'fast') return 'gemini-2.5-flash';
  return undefined;
}

export async function runAgentStepViaBackend(
  provider: AIProviderName,
  messages: Array<{ role: string; content?: string | null; tool_call_id?: string; tool_calls?: unknown[] }>,
  options: StreamChatOptions,
): Promise<AgentStepResult> {
  let model = options.model;
  if (!model || model === 'auto') {
    const resolved = provider === 'auto' ? resolveAutoProvider(String(messages[0]?.content || ''), options.agentMode) : provider;
    const autoModel = resolveAutoModel(String(messages[0]?.content || ''), options.agentMode);
    switch (resolved) {
      case 'claude':
        model = autoModel || 'claude-sonnet-4-20250514';
        break;
      case 'gemini':
        model = 'gemini-2.5-flash';
        break;
      default:
        model = undefined;
    }
  }

  const step = await apiClient.aiAgentStep({
    messages,
    context: { ...options.context, preferredProvider: provider !== 'auto' && provider !== 'mock' ? provider : undefined },
    model,
    conversationId: options.conversationId,
  });

  return step;
}

/** Mock agent for offline / no API key — simulates a real tool loop */
export async function* mockAgentStream(
  prompt: string,
  _messages: Array<{ role: string; content?: string | null }>,
): AsyncIterable<AgentEvent> {
  yield { type: 'status', text: 'Mock agent planning…' };
  await delay(400);
  yield { type: 'message_delta', text: 'Analyzing your request locally (no API key). ' };

  const lower = prompt.toLowerCase();
  if (lower.includes('list') || lower.includes('files') || lower.includes('explore')) {
    yield { type: 'status', text: 'Listing project directory…' };
    yield {
      type: 'tool_request',
      toolCall: {
        id: 'mock_list_1',
        type: 'function',
        function: { name: 'list_directory', arguments: JSON.stringify({ path: '.' }) },
      },
    };
    await delay(300);
    yield {
      type: 'tool_result',
      result: { tool_call_id: 'mock_list_1', content: '[dir] src\n[dir] node_modules\n[file] package.json', success: true },
    };
  }

  if (lower.includes('run') || lower.includes('build') || lower.includes('npm')) {
    yield { type: 'status', text: 'Preparing terminal command…' };
    const cmd = lower.includes('build') ? 'npm run build' : 'npm run dev';
    yield {
      type: 'tool_request',
      toolCall: {
        id: 'mock_term_1',
        type: 'function',
        function: { name: 'run_terminal', arguments: JSON.stringify({ command: cmd, title: 'Run command' }) },
      },
    };
    await delay(200);
  }

  if (lower.includes('fix') || lower.includes('edit') || lower.includes('create')) {
    yield { type: 'status', text: 'Preparing file edit…' };
    yield {
      type: 'tool_request',
      toolCall: {
        id: 'mock_write_1',
        type: 'function',
        function: {
          name: 'write_file',
          arguments: JSON.stringify({
            path: 'README-agent-demo.md',
            content: `# Agent Demo\n\nGenerated by mock agent for: ${prompt.slice(0, 80)}\n`,
          }),
        },
      },
    };
    await delay(200);
    yield {
      type: 'diff',
      filePath: 'README-agent-demo.md',
      oldText: '',
      newText: `# Agent Demo\n\nGenerated by mock agent for: ${prompt.slice(0, 80)}\n`,
    };
  }

  yield { type: 'message_delta', text: '\n\nMock run complete. Sign in via Settings for full AI agent capabilities.' };
  yield { type: 'done' };
}

export async function isMockMode(): Promise<boolean> {
  return !apiClient.getToken();
}

function delay(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}
